import Footer from '@/components/Footer'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Header from '../components/header'
import { AppProviders } from '../components/providers'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Wheather Widget',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background text-foreground`}
			>
				<AppProviders>
					<div className='min-h-screen flex flex-col'>
						<Header />
						<main className='flex-1 p-4'>{children}</main>
						<Footer />
					</div>
				</AppProviders>
			</body>
		</html>
	)
}
